/**
 * Tests for the full stack generation pipeline.
 */
import { assertEquals, assertStringIncludes } from "@std/assert";
import { generateStacks } from "./generate.ts";
import type { GenerateOptions } from "./generate.ts";

async function makeTempDir(): Promise<string> {
  return await Deno.makeTempDir({ prefix: "stackctl-test-generate-" });
}

async function writeFile(dir: string, name: string, content: string) {
  await Deno.writeTextFile(dir + "/" + name, content);
}

async function createFixture(repoRoot: string) {
  const svcDir = repoRoot + "/services/web";
  await Deno.mkdir(svcDir, { recursive: true });

  await writeFile(
    svcDir,
    "docker-compose.yml",
    [
      "x-stack: platform",
      "",
      "services:",
      "  web:",
      "    image: nginx:alpine",
      "    ports:",
      '      - "8080:80"',
      "    volumes:",
      '      - "./html:/usr/share/nginx/html"',
      '      - "app-data:/var/lib/data"',
      "    deploy:",
      "      replicas: 2",
      "",
      "volumes:",
      "  app-data:",
    ].join("\n"),
  );

  await writeFile(
    svcDir,
    "swarm.fragment.yml",
    [
      "services:",
      "  web:",
      "    logging:",
      "      driver: json-file",
      "",
    ].join("\n"),
  );
}

// ---------------------------------------------------------------------------
// Original tests
// ---------------------------------------------------------------------------

Deno.test("generateStacks: single stack dry-run returns content", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const result = await generateStacks({ stacks: ["platform"], repoRoot: tmp, dryRun: true });

  assertEquals(result.errors, []);
  assertEquals(Object.keys(result.generated).length, 1);

  const content = result.generated["platform"];
  assertStringIncludes(content, "# Generated by stackctl generate");
  assertStringIncludes(content, "web:");
  assertStringIncludes(content, "traefik-public");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: writes files when not dry-run", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const result = await generateStacks({
    stacks: ["platform"],
    repoRoot: tmp,
    outputDir: tmp + "/stacks",
    dryRun: false,
  });

  assertEquals(result.errors, []);
  assertEquals(result.files[0], tmp + "/stacks/platform.yml");

  const written = await Deno.readTextFile(tmp + "/stacks/platform.yml");
  assertStringIncludes(written, "# Generated by stackctl generate");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: generates all stacks when no filter", async () => {
  const tmp = await makeTempDir();
  const svcA = tmp + "/services/api";
  const svcB = tmp + "/services/db";
  await Deno.mkdir(svcA, { recursive: true });
  await Deno.mkdir(svcB, { recursive: true });

  await writeFile(
    svcA,
    "docker-compose.yml",
    ["x-stack: infra", "services:", "  api:", "    image: node:20"].join("\n"),
  );
  await writeFile(
    svcB,
    "docker-compose.yml",
    ["x-stack: platform", "services:", "  db:", "    image: postgres:16"].join("\n"),
  );

  const result = await generateStacks({ repoRoot: tmp, dryRun: true });

  assertEquals(result.errors, []);
  assertEquals(Object.keys(result.generated).length, 2);
  assertStringIncludes(result.generated["infra"], "api:");
  assertStringIncludes(result.generated["platform"], "db:");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: reports error for nonexistent stack", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const result = await generateStacks({ stacks: ["nonexistent"], repoRoot: tmp, dryRun: true });

  assertEquals(result.errors.length, 1);
  assertStringIncludes(result.errors[0], "nonexistent");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: warnings for empty repo", async () => {
  const tmp = await makeTempDir();

  const result = await generateStacks({ repoRoot: tmp, dryRun: true });

  assertEquals(result.warnings.length, 1);
  assertStringIncludes(result.warnings[0], "No stacks discovered");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: output contains default network", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const result = await generateStacks({ stacks: ["platform"], repoRoot: tmp, dryRun: true });

  const content = result.generated["platform"];
  assertStringIncludes(content, "networks:");
  assertStringIncludes(content, "default:");
  assertStringIncludes(content, "traefik-public");
  assertStringIncludes(content, "external: true");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: output includes named volumes as external", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const result = await generateStacks({ stacks: ["platform"], repoRoot: tmp, dryRun: true });

  const content = result.generated["platform"];
  assertStringIncludes(content, "volumes:");
  assertStringIncludes(content, "app-data:");
  assertStringIncludes(content, "external: true");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: services stripped of compose-only keys", async () => {
  const tmp = await makeTempDir();
  const svcDir = tmp + "/services/app";
  await Deno.mkdir(svcDir, { recursive: true });

  await writeFile(
    svcDir,
    "docker-compose.yml",
    [
      "x-stack: infra",
      "services:",
      "  app:",
      "    image: alpine",
      "    container_name: my-container",
      "    restart: always",
      "    build: .",
      "    deploy:",
      "      replicas: 1",
    ].join("\n"),
  );

  const result = await generateStacks({ stacks: ["infra"], repoRoot: tmp, dryRun: true });

  const content = result.generated["infra"];
  assertEquals(content.includes("container_name"), false);
  assertEquals(content.includes("restart:"), false);
  assertEquals(content.includes("build:"), false);
  assertStringIncludes(content, "deploy:");
  assertStringIncludes(content, "image: alpine");

  await Deno.remove(tmp, { recursive: true });
});

// ---------------------------------------------------------------------------
// Review-fix tests
// ---------------------------------------------------------------------------

Deno.test("generateStacks: custom network name from config", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const result = await generateStacks({
    stacks: ["platform"],
    repoRoot: tmp,
    dryRun: true,
    network: "custom-internal",
  });

  const content = result.generated["platform"];
  assertStringIncludes(content, "custom-internal");
  assertEquals(content.includes("traefik-public"), false);

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: honors configStackNames ordering", async () => {
  const tmp = await makeTempDir();
  const svcA = tmp + "/services/api";
  const svcB = tmp + "/services/db";
  await Deno.mkdir(svcA, { recursive: true });
  await Deno.mkdir(svcB, { recursive: true });

  await writeFile(
    svcA,
    "docker-compose.yml",
    ["x-stack: infra", "services:", "  api:", "    image: node:20"].join("\n"),
  );
  await writeFile(
    svcB,
    "docker-compose.yml",
    ["x-stack: platform", "services:", "  db:", "    image: postgres:16"].join("\n"),
  );

  const result = await generateStacks({
    configStackNames: ["platform", "infra"],
    repoRoot: tmp,
    dryRun: true,
  });

  assertEquals(result.errors, []);
  assertEquals(Object.keys(result.generated), ["platform", "infra"]);

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: per-service composeDir path rewriting", async () => {
  const tmp = await makeTempDir();
  const svcA = tmp + "/services/web";
  const svcB = tmp + "/services/api";
  await Deno.mkdir(svcA, { recursive: true });
  await Deno.mkdir(svcB, { recursive: true });

  await writeFile(
    svcA,
    "docker-compose.yml",
    [
      "x-stack: platform",
      "services:",
      "  web:",
      "    image: nginx:alpine",
      "    env_file: .env",
      "    volumes:",
      '      - "./html:/usr/share/nginx/html"',
    ].join("\n"),
  );
  await writeFile(
    svcB,
    "docker-compose.yml",
    [
      "x-stack: platform",
      "services:",
      "  api:",
      "    image: node:20",
      "    env_file: .env.prod",
      "    volumes:",
      '      - "./config:/app/config"',
    ].join("\n"),
  );

  const result = await generateStacks({ stacks: ["platform"], repoRoot: tmp, dryRun: true });

  const content = result.generated["platform"];
  assertStringIncludes(content, "services/web/.env");
  assertStringIncludes(content, "services/api/.env.prod");
  assertStringIncludes(content, "services/web/html");
  assertStringIncludes(content, "services/api/config");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: preserves volume metadata from compose file", async () => {
  const tmp = await makeTempDir();
  const svcDir = tmp + "/services/web";
  await Deno.mkdir(svcDir, { recursive: true });

  await writeFile(
    svcDir,
    "docker-compose.yml",
    [
      "x-stack: platform",
      "",
      "services:",
      "  web:",
      "    image: nginx:alpine",
      "    volumes:",
      '      - "app-data:/var/lib/data"',
      "",
      "volumes:",
      "  app-data:",
      "    name: platform_data",
      "    driver: local",
      "    driver_opts:",
      "      type: none",
      "      device: /mnt/data",
      "      o: bind",
    ].join("\n"),
  );

  const result = await generateStacks({ stacks: ["platform"], repoRoot: tmp, dryRun: true });

  const content = result.generated["platform"];
  assertStringIncludes(content, "name: platform_data");
  assertStringIncludes(content, "driver: local");
  assertStringIncludes(content, "external: true");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: snapshot - generates deterministic output", async () => {
  const tmp = await makeTempDir();
  const svcDir = tmp + "/services/app";
  await Deno.mkdir(svcDir, { recursive: true });
  await writeFile(
    svcDir,
    "docker-compose.yml",
    [
      "x-stack: core",
      "",
      "services:",
      "  app:",
      "    image: nginx:alpine",
      "    ports:",
      '      - "8080:80"',
      "    deploy:",
      "      replicas: 1",
    ].join("\n"),
  );

  const outputDir = tmp + "/stacks";
  const result = await generateStacks({
    stacks: ["core"],
    repoRoot: tmp,
    outputDir,
    dryRun: false,
  });

  assertEquals(result.errors, []);
  assertEquals(result.files.length, 1);

  const generated = await Deno.readTextFile(outputDir + "/core.yml");

  const expected = [
    "# Generated by stackctl generate — do not edit manually.",
    "networks:",
    "  default:",
    "    external: true",
    "    name: traefik-public",
    "services:",
    "  app:",
    "    deploy:",
    "      replicas: 1",
    "    image: 'nginx:alpine'",
    "    logging:",
    "      driver: local",
    "      options:",
    "        max-file: 3",
    "        max-size: 10m",
    "    ports:",
    "      - '8080:80'",
  ].join("\n") + "\n";

  assertEquals(generated, expected);

  await Deno.remove(tmp, { recursive: true });
});
