/**
 * Tests for the full stack generation pipeline.
 */
import { assertEquals, assertStringIncludes } from "@std/assert";
import { generateStacks } from "./generate.ts";
import type { GenerateOptions } from "./generate.ts";

async function makeTempDir(): Promise<string> {
  return await Deno.makeTempDir({ prefix: "stackctl-test-generate-" });
}

async function writeFile(dir: string, name: string, content: string) {
  await Deno.writeTextFile(`${dir}/${name}`, content);
}

async function createFixture(repoRoot: string) {
  // Create a service directory with compose + fragment
  const svcDir = `${repoRoot}/services/web`;
  await Deno.mkdir(svcDir, { recursive: true });

  await writeFile(
    svcDir,
    "docker-compose.yml",
    [
      "x-stack: platform",
      "",
      "services:",
      "  web:",
      "    image: nginx:alpine",
      "    ports:",
      '      - "8080:80"',
      "    volumes:",
      '      - "./html:/usr/share/nginx/html"',
      '      - "app-data:/var/lib/data"',
      "    deploy:",
      "      replicas: 2",
      "",
      "volumes:",
      "  app-data:",
    ].join("\n"),
  );

  await writeFile(
    svcDir,
    "swarm.fragment.yml",
    [
      "services:",
      "  web:",
      "    logging:",
      "      driver: json-file",
      "",
    ].join("\n"),
  );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

Deno.test("generateStacks: single stack dry-run returns content", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const options: GenerateOptions = {
    stacks: ["platform"],
    repoRoot: tmp,
    dryRun: true,
  };

  const result = await generateStacks(options);

  assertEquals(result.errors, []);
  assertEquals(Object.keys(result.generated).length, 1);
  assertEquals(result.files.length, 1);

  const content = result.generated["platform"];
  // Should have the header comment
  assertStringIncludes(content, "# Generated by stackctl generate");
  // Should contain the service
  assertStringIncludes(content, "web:");
  // Should have the network block
  assertStringIncludes(content, "traefik-public");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: writes files when not dry-run", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const options: GenerateOptions = {
    stacks: ["platform"],
    repoRoot: tmp,
    outputDir: `${tmp}/stacks`,
    dryRun: false,
  };

  const result = await generateStacks(options);

  assertEquals(result.errors, []);
  assertEquals(result.files.length, 1);
  assertEquals(result.files[0], `${tmp}/stacks/platform.yml`);

  // Verify file was actually written
  const written = await Deno.readTextFile(`${tmp}/stacks/platform.yml`);
  assertStringIncludes(written, "# Generated by stackctl generate");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: generates all stacks when no filter", async () => {
  const tmp = await makeTempDir();

  // Create two stacks
  const svcA = `${tmp}/services/api`;
  const svcB = `${tmp}/services/db`;
  await Deno.mkdir(svcA, { recursive: true });
  await Deno.mkdir(svcB, { recursive: true });

  await writeFile(
    svcA,
    "docker-compose.yml",
    [
      "x-stack: infra",
      "services:",
      "  api:",
      "    image: node:20",
    ].join("\n"),
  );

  await writeFile(
    svcB,
    "docker-compose.yml",
    [
      "x-stack: platform",
      "services:",
      "  db:",
      "    image: postgres:16",
    ].join("\n"),
  );

  const options: GenerateOptions = {
    repoRoot: tmp,
    dryRun: true,
  };

  const result = await generateStacks(options);

  assertEquals(result.errors, []);
  assertEquals(Object.keys(result.generated).length, 2);

  const content1 = result.generated["infra"];
  const content2 = result.generated["platform"];
  assertStringIncludes(content1, "api:");
  assertStringIncludes(content2, "db:");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: reports error for nonexistent stack", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const options: GenerateOptions = {
    stacks: ["nonexistent"],
    repoRoot: tmp,
    dryRun: true,
  };

  const result = await generateStacks(options);

  assertEquals(result.errors.length, 1);
  assertStringIncludes(result.errors[0], "nonexistent");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: warnings for empty repo", async () => {
  const tmp = await makeTempDir();

  const options: GenerateOptions = {
    repoRoot: tmp,
    dryRun: true,
  };

  const result = await generateStacks(options);

  assertEquals(result.warnings.length, 1);
  assertStringIncludes(result.warnings[0], "No stacks discovered");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: output contains default network", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const result = await generateStacks({ stacks: ["platform"], repoRoot: tmp, dryRun: true });

  const content = result.generated["platform"];
  assertStringIncludes(content, "networks:");
  assertStringIncludes(content, "default:");
  assertStringIncludes(content, "traefik-public");
  assertStringIncludes(content, "external: true");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: output includes named volumes as external", async () => {
  const tmp = await makeTempDir();
  await createFixture(tmp);

  const result = await generateStacks({ stacks: ["platform"], repoRoot: tmp, dryRun: true });

  const content = result.generated["platform"];
  assertStringIncludes(content, "volumes:");
  assertStringIncludes(content, "app-data:");
  assertStringIncludes(content, "external: true");

  await Deno.remove(tmp, { recursive: true });
});

Deno.test("generateStacks: services stripped of compose-only keys", async () => {
  const tmp = await makeTempDir();
  const svcDir = `${tmp}/services/app`;
  await Deno.mkdir(svcDir, { recursive: true });

  await writeFile(
    svcDir,
    "docker-compose.yml",
    [
      "x-stack: infra",
      "services:",
      "  app:",
      "    image: alpine",
      "    container_name: my-container",
      "    restart: always",
      "    build: .",
      "    deploy:",
      "      replicas: 1",
    ].join("\n"),
  );

  const result = await generateStacks({ stacks: ["infra"], repoRoot: tmp, dryRun: true });

  const content = result.generated["infra"];
  // container_name, restart, build must NOT appear
  assertEquals(content.includes("container_name"), false);
  assertEquals(content.includes("restart:"), false);
  assertEquals(content.includes("build:"), false);
  // deploy and image must stay
  assertStringIncludes(content, "deploy:");
  assertStringIncludes(content, "image: alpine");

  await Deno.remove(tmp, { recursive: true });
});
