/**
 * Tests for the config-first reload pipeline.
 *
 * Uses FakeProcessRunner — never talks to real Docker.
 *
 * Coverage:
 *   - Default always-deploys (no checksum skip)
 *   - Opt-in --skip-unchanged
 *   - Dry-run logging
 *   - Force-service-update
 *   - Safety: no remove commands are ever scheduled
 */
import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { FakeProcessRunner, FakeProcessRunnerBuilder } from "../testing/fakes.ts";
import { reloadStacks } from "./reload.ts";
import type { ResolvedConfig } from "../config/types.ts";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface StackEntry {
  name: string;
  content: string;
  /** If true, also write a pre-existing .rendered file with same content. */
  preRendered?: boolean;
  /** If set, pre-existing .rendered file has this content (for diff detection). */
  preRenderedContent?: string;
}

/**
 * Set up a temporary directory with:
 * - A `.stackctl` config
 * - Service compose files (x-stack tagged)
 * - Generated stack files in `stacks/`
 * - Optionally pre-rendered files in `.rendered/`
 */
async function setupProject(entries: StackEntry[]): Promise<{
  tmp: string;
  config: ResolvedConfig;
  cleanup: () => Promise<void>;
}> {
  const tmp = await Deno.makeTempDir({ prefix: "stackctl-reload-test-" });

  // Write .stackctl config
  const stackNames = entries.map((e) => e.name);
  const configYaml = [
    "project: test-project",
    "stack:",
    "  directory: stacks",
    `  names: [${stackNames.join(", ")}]`,
    "  network: traefik-public",
    "render:",
    "  outputDirectory: .rendered",
    "env:",
    "  activeName: .env",
  ].join("\n");
  await Deno.writeTextFile(`${tmp}/.stackctl`, configYaml);

  // Write service compose files with x-stack
  for (const entry of entries) {
    const svcDir = `${tmp}/services/${entry.name}-svc`;
    await Deno.mkdir(svcDir, { recursive: true });
    await Deno.writeTextFile(
      `${svcDir}/docker-compose.yml`,
      [
        `x-stack: ${entry.name}`,
        "services:",
        `  ${entry.name}-svc:`,
        "    image: nginx:alpine",
        `    content: "${entry.content}"`,
      ].join("\n"),
    );
  }

  // Write generated stacks to stacks/ dir (simulating prior generate)
  const stacksDir = `${tmp}/stacks`;
  await Deno.mkdir(stacksDir, { recursive: true });
  for (const entry of entries) {
    const generated = [
      "# Generated by stackctl generate — do not edit manually.",
      "services:",
      `  ${entry.name}-svc:`,
      "    image: nginx:alpine",
      `    content: "${entry.content}"`,
      "networks:",
      "  default:",
      "    name: traefik-public",
      "    external: true",
    ].join("\n");
    await Deno.writeTextFile(`${stacksDir}/${entry.name}.yml`, generated);
  }

  // Optionally write pre-rendered files
  const renderedDir = `${tmp}/.rendered`;
  for (const entry of entries) {
    if (entry.preRendered) {
      await Deno.mkdir(renderedDir, { recursive: true });
      const content = entry.preRenderedContent ?? [
        `# Rendered by stackctl reload`,
        "services:",
        `  ${entry.name}-svc:`,
        "    image: nginx:alpine",
        `    content: "${entry.content}"`,
        "networks:",
        "  default:",
        "    name: traefik-public",
        "    external: true",
      ].join("\n");
      await Deno.writeTextFile(
        `${renderedDir}/${entry.name}.rendered.yml`,
        content,
      );
    }
  }

  // Build a minimal ResolvedConfig pointing to the temp dir
  const config: ResolvedConfig = {
    base: {
      project: "test-project",
      repoRoot: tmp,
      stack: {
        directory: "stacks",
        names: stackNames,
        network: "traefik-public",
      },
      render: { outputDirectory: ".rendered" },
      env: { activeName: ".env" },
    },
    overrides: [],
  };

  return {
    tmp,
    config,
    cleanup: async () => {
      await Deno.remove(tmp, { recursive: true });
    },
  };
}

/** Create a FakeProcessRunner that responds to docker stack deploy with success. */
function deploySuccessRunner(): FakeProcessRunner {
  return new FakeProcessRunnerBuilder()
    .addResponse({
      match: ["docker", "stack", "deploy"],
      result: { stdout: "deploying...", stderr: "", code: 0, success: true, command: [] },
    })
    .build();
}

/**
 * Create a runner that supports docker stack deploy AND docker stack services (JSON).
 */
function deployAndServicesRunner(): FakeProcessRunner {
  return new FakeProcessRunnerBuilder()
    .addResponse({
      match: ["docker", "stack", "deploy"],
      result: { stdout: "deploying...", stderr: "", code: 0, success: true, command: [] },
    })
    .addResponse({
      match: ["docker", "stack", "services"],
      result: {
        stdout: `{"Name":"platform-svc","Mode":"replicated"}\n`,
        stderr: "",
        code: 0,
        success: true,
        command: [],
      },
    })
    .addResponse({
      match: ["docker", "service", "update"],
      result: { stdout: "updated", stderr: "", code: 0, success: true, command: [] },
    })
    .build();
}

// ---------------------------------------------------------------------------
// Issue 1: Default always-deploys (no checksum skip)
// ---------------------------------------------------------------------------

Deno.test("reload: default always deploys even when rendered output unchanged", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner1 = deploySuccessRunner();
  const runner2 = deploySuccessRunner();

  try {
    // First run: deploys and writes the .rendered file
    await reloadStacks({ config, runner: runner1, skipGenerate: true });
    assertEquals(runner1.containsCommand(["docker", "stack", "deploy"]), true);

    // Second run: by default should STILL deploy (no checksum skip)
    const results = await reloadStacks({
      config,
      runner: runner2,
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].stack, "platform");
    assertEquals(results[0].action, "deployed");
    assertEquals(runner2.containsCommand(["docker", "stack", "deploy"]), true);
  } finally {
    await cleanup();
  }
});

// ---------------------------------------------------------------------------
// Issue 1: Opt-in checksum skipping with --skip-unchanged
// ---------------------------------------------------------------------------

Deno.test("reload: skipUnchanged=true skips stacks whose rendered output is unchanged", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  try {
    // First run: deploys and writes the .rendered file
    await reloadStacks({ config, runner: deploySuccessRunner(), skipGenerate: true });

    // Second run with skipUnchanged=true should detect unchanged
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
      skipUnchanged: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].stack, "platform");
    assertEquals(results[0].action, "unchanged");
    assertEquals(runner.containsCommand(["docker", "stack", "deploy"]), false);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: skipUnchanged=true deploys when content has changed", async () => {
  const { config, cleanup } = await setupProject([
    {
      name: "platform",
      content: "v1",
      preRendered: true,
      preRenderedContent: "# old content",
    },
  ]);
  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
      skipUnchanged: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].stack, "platform");
    assertEquals(results[0].action, "deployed");
    assertEquals(runner.containsCommand(["docker", "stack", "deploy"]), true);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: skipUnchanged=true dry-run shows would-skip for unchanged stacks", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);

  try {
    // First run: deploy to write the .rendered file
    await reloadStacks({
      config,
      runner: deploySuccessRunner(),
      skipGenerate: true,
    });

    // Second run: dry-run with skipUnchanged should show would-skip
    const results = await reloadStacks({
      config,
      runner: deploySuccessRunner(),
      dryRun: true,
      skipGenerate: true,
      skipUnchanged: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].action, "would-skip");
  } finally {
    await cleanup();
  }
});

// ---------------------------------------------------------------------------
// Issue 4: Safety — no remove commands ever scheduled
// ---------------------------------------------------------------------------

Deno.test("reload: never schedules docker stack rm commands", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  try {
    await reloadStacks({ config, runner, skipGenerate: true });

    // Assert no docker stack rm command was recorded
    assertEquals(runner.containsCommand(["docker", "stack", "rm"]), false);
    assertEquals(runner.containsCommand(["docker", "network", "rm"]), false);
    assertEquals(runner.containsCommand(["docker", "volume", "rm"]), false);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: never schedules remove commands even in dry-run", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  try {
    await reloadStacks({
      config,
      runner,
      skipGenerate: true,
      dryRun: true,
    });

    // Assert no remove commands
    assertEquals(runner.containsCommand(["docker", "stack", "rm"]), false);
    assertEquals(runner.containsCommand(["docker", "network", "rm"]), false);
    assertEquals(runner.containsCommand(["docker", "volume", "rm"]), false);

    // But deploy command should not have been executed either
    assertEquals(runner.containsCommand(["docker", "stack", "deploy"]), false);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: deploys when no existing rendered file", async () => {
  const { config, tmp, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  // Ensure no .rendered directory exists
  try {
    await Deno.remove(`${tmp}/.rendered`, { recursive: true });
  } catch { /* ok */ }

  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].action, "deployed");

    // Verify rendered file was created
    const rendered = await Deno.readTextFile(`${tmp}/.rendered/platform.rendered.yml`);
    assertStringIncludes(rendered, "platform-svc");
  } finally {
    await cleanup();
  }
});

// ---------------------------------------------------------------------------
// Issue 5: Dry-run shows each step
// ---------------------------------------------------------------------------

Deno.test("reload: dry-run shows changes without deploying", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      dryRun: true,
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].stack, "platform");
    assertEquals(results[0].action, "would-deploy");
    // In dry-run, no docker deploy should have been attempted
    assertEquals(runner.containsCommand(["docker", "stack", "deploy"]), false);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: dry-run unchanged followed by real run deploys", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1", preRendered: true, preRenderedContent: "# old" },
  ]);

  try {
    // First: dry-run should say would-deploy (no checksum by default)
    const dryResults = await reloadStacks({
      config,
      runner: deploySuccessRunner(),
      dryRun: true,
      skipGenerate: true,
    });
    assertEquals(dryResults[0].action, "would-deploy");

    // Second: real run should deploy
    const realRunner = deploySuccessRunner();
    const results = await reloadStacks({
      config,
      runner: realRunner,
      skipGenerate: true,
    });
    assertEquals(results[0].action, "deployed");
    assertEquals(realRunner.containsCommand(["docker", "stack", "deploy"]), true);
  } finally {
    await cleanup();
  }
});

// ---------------------------------------------------------------------------
// Existing tests (adapted for new default behavior)
// ---------------------------------------------------------------------------

Deno.test("reload: changed stacks are deployed", async () => {
  const { config, tmp, cleanup } = await setupProject([
    {
      name: "platform",
      content: "v1",
      preRendered: true,
      preRenderedContent: "# different content",
    },
  ]);
  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].stack, "platform");
    assertEquals(results[0].action, "deployed");
    assertEquals(runner.containsCommand(["docker", "stack", "deploy"]), true);

    // Verify the .rendered file was updated
    const rendered = await Deno.readTextFile(`${tmp}/.rendered/platform.rendered.yml`);
    assertStringIncludes(rendered, "Rendered by stackctl reload");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: skip-generate uses existing stack files", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].action, "deployed");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: generates when skip-generate is false", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: false,
    });

    assertEquals(results.length, 1);
    assert(results[0].action === "deployed" || results[0].action === "error");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: stacks filter only reloads requested stacks", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
    { name: "infra", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  try {
    // Reload only "platform"
    const results = await reloadStacks({
      config,
      runner,
      stacks: ["platform"],
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].stack, "platform");
    assertEquals(results[0].action, "deployed");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: handles missing rendered directory", async () => {
  const { config, tmp, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  // Ensure no .rendered directory exists
  try {
    await Deno.remove(`${tmp}/.rendered`, { recursive: true });
  } catch { /* ok */ }

  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].action, "deployed");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: deployment failure is reported as error", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = new FakeProcessRunnerBuilder()
    .addResponse({
      match: ["docker", "stack", "deploy"],
      result: {
        stdout: "",
        stderr: "deploy failed: network error",
        code: 1,
        success: false,
        command: [],
      },
    })
    .build();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].action, "error");
    assertEquals(results[0].error, "deploy failed: network error");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: reports error for missing stack file", async () => {
  const { config, tmp, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  // Remove the generated stack file
  await Deno.remove(`${tmp}/stacks/platform.yml`);

  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].action, "error");
    assertStringIncludes(results[0].error!, "Stack file not found");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: handles multiple stacks with mixed results", async () => {
  const { config, tmp, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
    { name: "infra", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  try {
    // First run: deploy both stacks to write .rendered files
    await reloadStacks({
      config,
      runner: deploySuccessRunner(),
      skipGenerate: true,
    });

    // Modify the generated stack file for "infra" so it differs on next render
    const infraStackFile = `${tmp}/stacks/infra.yml`;
    const origContent = await Deno.readTextFile(infraStackFile);
    await Deno.writeTextFile(infraStackFile, origContent.replace('content: "v1"', 'content: "v2"'));

    // Second run: both should deploy (default behavior)
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 2);

    const platform = results.find((r) => r.stack === "platform")!;
    const infra = results.find((r) => r.stack === "infra")!;

    // Default behavior: always deploys
    assertEquals(platform.action, "deployed");
    assertEquals(infra.action, "deployed");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: handles empty stack list gracefully", async () => {
  const { config, cleanup } = await setupProject([]);
  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 0);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: with overrides passed from CLI", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  // Write an override file
  const overridePath = `${config.base.repoRoot}/override.yml`;
  await Deno.writeTextFile(overridePath, "services:\n  extra: {}\n");

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: false,
      overrides: [{ source: "explicit" as const, path: overridePath }],
    });

    assertEquals(results.length, 1);
    assert(results[0].action === "deployed" || results[0].action === "error");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: handles generation errors gracefully", async () => {
  const { config, tmp, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  await Deno.remove(`${tmp}/services`, { recursive: true });
  await Deno.remove(`${tmp}/stacks`, { recursive: true });

  const runner = deploySuccessRunner();

  try {
    const cfg: ResolvedConfig = {
      base: {
        ...config.base,
        stack: { ...config.base.stack, names: ["nonexistent"] },
      },
      overrides: [],
    };

    const results = await reloadStacks({
      config: cfg,
      runner,
      skipGenerate: false,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].stack, "nonexistent");
    assertEquals(results[0].action, "error");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: verifies rendered file content after deploy", async () => {
  const { config, tmp, cleanup } = await setupProject([
    { name: "platform", content: "after-reload" },
  ]);
  const runner = deploySuccessRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results[0].action, "deployed");

    const rendered = await Deno.readTextFile(`${tmp}/.rendered/platform.rendered.yml`);
    assertStringIncludes(rendered, "Rendered by stackctl reload");
    assertStringIncludes(rendered, "platform-svc");
    assertStringIncludes(rendered, "after-reload");
  } finally {
    await cleanup();
  }
});

Deno.test("reload: multiple deployments with only partial changes", async () => {
  const { config, tmp, cleanup } = await setupProject([
    { name: "alpha", content: "v1" },
    { name: "beta", content: "old" },
    { name: "gamma", content: "v3" },
  ]);
  const runner = deploySuccessRunner();

  try {
    // First run: deploy all three stacks so .rendered files are written
    await reloadStacks({
      config,
      runner: deploySuccessRunner(),
      skipGenerate: true,
    });

    // Modify only "beta"'s generated stack file
    const betaStackFile = `${tmp}/stacks/beta.yml`;
    const origContent = await Deno.readTextFile(betaStackFile);
    await Deno.writeTextFile(
      betaStackFile,
      origContent.replace('content: "old"', 'content: "new"'),
    );

    // Second run: default behavior always deploys all
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
    });

    assertEquals(results.length, 3);
    assertEquals(results.find((r) => r.stack === "alpha")!.action, "deployed");
    assertEquals(results.find((r) => r.stack === "beta")!.action, "deployed");
    assertEquals(results.find((r) => r.stack === "gamma")!.action, "deployed");
  } finally {
    await cleanup();
  }
});

// ---------------------------------------------------------------------------
// Issue 3: Force service update
// ---------------------------------------------------------------------------

Deno.test("reload: forceServiceUpdate calls docker service update --force", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deployAndServicesRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
      forceServiceUpdate: true,
    });

    assertEquals(results[0].action, "deployed");
    assertEquals(runner.containsCommand(["docker", "service", "update", "--force"]), true);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: forceServiceUpdate=false does not call docker service update", async () => {
  const { config, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deployAndServicesRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
      forceServiceUpdate: false,
    });

    assertEquals(results[0].action, "deployed");
    assertEquals(runner.containsCommand(["docker", "service", "update"]), false);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: forceServiceUpdate respects config base.commands.reload.forceServiceUpdate", async () => {
  const { config: baseConfig, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);

  const config: ResolvedConfig = {
    ...baseConfig,
    base: {
      ...baseConfig.base,
      commands: {
        reload: { forceServiceUpdate: true },
      },
    },
  };

  const runner = deployAndServicesRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
      // Not setting forceServiceUpdate — should come from config
    });

    assertEquals(results[0].action, "deployed");
    assertEquals(runner.containsCommand(["docker", "service", "update", "--force"]), true);
  } finally {
    await cleanup();
  }
});

Deno.test("reload: CLI forceServiceUpdate overrides config", async () => {
  const { config: baseConfig, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);

  // Config says force=true, but CLI says force=false
  const config: ResolvedConfig = {
    ...baseConfig,
    base: {
      ...baseConfig.base,
      commands: {
        reload: { forceServiceUpdate: true },
      },
    },
  };

  const runner = deployAndServicesRunner();

  try {
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
      forceServiceUpdate: false, // CLI flag overrides config
    });

    assertEquals(results[0].action, "deployed");
    assertEquals(runner.containsCommand(["docker", "service", "update"]), false);
  } finally {
    await cleanup();
  }
});

// ---------------------------------------------------------------------------
// Edge case: checksum comparison ignores header comments
// (still valid for skipUnchanged mode)
// ---------------------------------------------------------------------------

Deno.test("reload: skipUnchanged checksum comparison is byte-level", async () => {
  const { config, tmp, cleanup } = await setupProject([
    { name: "platform", content: "v1" },
  ]);
  const runner = deploySuccessRunner();

  // Write a pre-rendered file with a different header but same body
  await Deno.mkdir(`${tmp}/.rendered`, { recursive: true });
  await Deno.writeTextFile(
    `${tmp}/.rendered/platform.rendered.yml`,
    [
      "# Completely different header from old version",
      "services:",
      "  platform-svc:",
      "    image: nginx:alpine",
      `    content: "v1"`,
      "networks:",
      "  default:",
      "    name: traefik-public",
      "    external: true",
    ].join("\n"),
  );

  try {
    // Different header → different checksum → should deploy when skipUnchanged=true
    const results = await reloadStacks({
      config,
      runner,
      skipGenerate: true,
      skipUnchanged: true,
    });

    assertEquals(results.length, 1);
    assertEquals(results[0].action, "deployed");
  } finally {
    await cleanup();
  }
});
