/**
 * Config initialisation — generates `.stackctl` template files.
 *
 * Includes:
 * - A default template with extensive inline comments
 * - Optional auto-detection from docker-compose files
 * - Preset configurations (minimal, standard)
 * - Profile and force/dry-run support
 */
import { exists } from "@std/fs";
import { parse as parseYaml } from "@std/yaml";
import { basename, join } from "@std/path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface InitOptions {
  /** Auto-detect layout from existing docker-compose files. */
  detect?: boolean;
  /** Preset template name (e.g. "minimal", "standard"). */
  preset?: string;
  /** Also create a profile config file. */
  profile?: string;
  /** Overwrite existing files. */
  force?: boolean;
  /** Print what would be written without writing. */
  dryRun?: boolean;
  /** Working directory. */
  cwd?: string;
}

export interface InitResult {
  /** Files that were (or would be) written. */
  written: string[];
  /** Errors encountered during initialisation. */
  errors: string[];
}

// ---------------------------------------------------------------------------
// Template (raw YAML with inline comments)
// ---------------------------------------------------------------------------

const TEMPLATE = `# stackctl configuration
# Generated by \`stackctl init\`
# See https://github.com/AniTrend/stackctl for documentation

# Project name used for stack naming and identification.
# This should match your repository or project name.
project: ""

# Stack generation settings
stack:
  # Subdirectory for generated stack files (default: "stacks")
  directory: "stacks"
  # Stack names to generate (one per service group).
  # These are the top-level stack names, not individual services.
  names:
    - "example"      # Replace with your stack names
  # Compose metadata key for stack grouping (default: "x-stack")
  composeStackKey: "x-stack"
  # Directories to skip during service discovery
  skipDirectories: []
  # External overlay network name for all stacks
  network: ""
  # Network driver (default: "overlay")
  networkDriver: "overlay"

# Rendering settings for env var interpolation
render:
  # Output directory for rendered files (default: ".rendered")
  outputDirectory: ".rendered"

# Environment file settings
env:
  # Active .env file name (default: ".env")
  activeName: ".env"
  # Allow plaintext profile env files (default: false)
  allowPlaintextProfiles: false

# (Optional) Secrets management with SOPS/age
# secrets:
#   encryptedFileName: ".env.enc"

# (Optional) Command-specific defaults
# commands:
#   up:
#     followLogs: true
#   reload:
#     followLogs: false
#     autoGenerate: true
#     forceServiceUpdate: false
`;

const MINIMAL_TEMPLATE = `# stackctl minimal configuration
# Generated by \`stackctl init --preset minimal\`
# See https://github.com/AniTrend/stackctl for documentation

project: ""

stack:
  directory: "stacks"
  names:
    - "app"
  network: ""

render:
  outputDirectory: ".rendered"

env:
  activeName: ".env"
`;

// ---------------------------------------------------------------------------
// Presets
// ---------------------------------------------------------------------------

const PRESETS: Record<string, string> = {
  minimal: MINIMAL_TEMPLATE,
  standard: TEMPLATE,
};

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

/**
 * Generate one or more `.stackctl` configuration files.
 *
 * Behaviour:
 * - Writes the base `.stackctl` file (with `--force` to overwrite).
 * - If `--profile` is set, also writes `.stackctl.<profile>`.
 * - `--detect` scans for docker-compose files to pre-populate values.
 * - `--dry-run` prints what would happen without writing.
 */
export async function initConfig(options: InitOptions): Promise<InitResult> {
  const cwd = options.cwd ?? Deno.cwd();
  const result: InitResult = { written: [], errors: [] };

  // Pick the template
  let template = TEMPLATE;
  if (options.preset && PRESETS[options.preset]) {
    template = PRESETS[options.preset];
  } else if (options.preset) {
    result.errors.push(
      `Unknown preset: "${options.preset}". Available: ${Object.keys(PRESETS).join(", ")}`,
    );
    return result;
  }

  // Auto-detect layout from docker-compose files
  if (options.detect) {
    template = await applyDetection(template, cwd);
  }

  // Write base config
  const basePath = join(cwd, ".stackctl");
  await writeConfigFile(basePath, template, options, result);

  // Write profile config if requested
  if (options.profile) {
    const profilePath = join(cwd, `.stackctl.${options.profile}`);
    await writeConfigFile(profilePath, template, options, result);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function writeConfigFile(
  path: string,
  content: string,
  options: InitOptions,
  result: InitResult,
): Promise<void> {
  const alreadyExists = await exists(path);

  if (alreadyExists && !options.force) {
    result.errors.push(
      `File already exists: ${path}. Use --force to overwrite.`,
    );
    return;
  }

  if (options.dryRun) {
    result.written.push(path);
    return;
  }

  try {
    await Deno.writeTextFile(path, content);
    result.written.push(path);
  } catch (err: unknown) {
    result.errors.push(
      `Failed to write ${path}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * Scan the working directory for docker-compose files and
 * attempt to pre-populate stack names and network from them.
 */
async function applyDetection(template: string, cwd: string): Promise<string> {
  // Scan for docker-compose.yml / .yaml files in the first level of cwd
  const composeFiles: string[] = [];
  for await (const entry of Deno.readDir(cwd)) {
    if (entry.isFile) {
      const name = entry.name;
      if (
        name === "docker-compose.yml" ||
        name === "docker-compose.yaml" ||
        name === "compose.yml" ||
        name === "compose.yaml" ||
        (name.startsWith("docker-compose.") &&
          (name.endsWith(".yml") || name.endsWith(".yaml")))
      ) {
        composeFiles.push(join(cwd, name));
      }
    }
  }

  if (composeFiles.length === 0) return template;

  // Try to parse the first compose file to extract useful info
  const stackNames: string[] = [];
  let network = "";

  for (const file of composeFiles) {
    try {
      const raw = await Deno.readTextFile(file);
      const parsed = parseYaml(raw) as Record<string, unknown>;

      if (parsed?.services && typeof parsed.services === "object") {
        for (const svcName of Object.keys(parsed.services as Record<string, unknown>)) {
          if (!stackNames.includes(svcName)) {
            stackNames.push(svcName);
          }
        }
      }

      if (!network && parsed?.networks && typeof parsed.networks === "object") {
        const nets = parsed.networks as Record<string, unknown>;
        const keys = Object.keys(nets);
        // Exclude default networks
        const custom = keys.find((k) => k !== "default" && k !== "bridge" && k !== "host");
        if (custom) network = custom;
        else if (keys.length > 0) {
          const first = keys[0];
          if (first !== "default") network = first;
        }
      }
    } catch {
      // Skip unparseable files during detection
    }
  }

  // Inject detected values into the template string
  let result = template;

  if (stackNames.length > 0) {
    const namesYaml = stackNames.map((n) => `      - "${n}"`).join("\n");
    // Replace the example name in the names array
    result = result.replace(
      /\n\s+names:\n(\s+- "example".*\n)+/,
      `\n    names:\n${namesYaml}\n`,
    );
  }

  if (network) {
    // Replace the empty network value
    result = result.replace(
      /\n\s+network: ""/,
      `\n    network: "${network}"`,
    );
  }

  // Derive project name from directory
  const dirName = basename(cwd);
  if (dirName && dirName !== "." && dirName !== "/") {
    result = result.replace(
      /^project: ""$/m,
      `project: "${dirName}"`,
    );
  }

  return result;
}
