/**
 * Config initialisation - generates `.stackctl` template files.
 *
 * Includes:
 * - A default template with extensive inline comments
 * - Optional auto-detection from docker-compose files
 * - Preset configurations (minimal, standard)
 * - Profile and force/dry-run support
 * - .gitignore management integration
 */
import { exists } from "@std/fs";
import { parse as parseYaml } from "@std/yaml";
import { basename, join } from "@std/path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface InitOptions {
  /** Auto-detect layout from existing docker-compose files. */
  detect?: boolean;
  /** Preset template name (e.g. "minimal", "standard"). */
  preset?: string;
  /** Also create a profile config file. */
  profile?: string;
  /** Append .stackctl.local and .env entries to .gitignore. */
  writeGitignore?: boolean;
  /** Overwrite existing files. */
  force?: boolean;
  /** Print what would be written without writing. */
  dryRun?: boolean;
  /** Working directory. */
  cwd?: string;
}

export interface InitResult {
  /** Files that were (or would be) written. */
  written: string[];
  /** Errors encountered during initialisation. */
  errors: string[];
}

// ---------------------------------------------------------------------------
// Template (raw YAML with inline comments)
// ---------------------------------------------------------------------------

const TEMPLATE = `# stackctl configuration
# Generated by \`stackctl init\`
# See https://github.com/AniTrend/stackctl for documentation

# Project name used for stack naming and identification.
# This should match your repository or project name.
project: ""

# Stack generation settings
stack:
  # Subdirectory for generated stack files (default: "stacks")
  directory: "stacks"
  # Stack names to generate (one per service group).
  # These are the top-level stack names, not individual services.
  names:
    - "example"      # Replace with your stack names
  # Compose metadata key for stack grouping (default: "x-stack")
  composeStackKey: "x-stack"
  # Directories to skip during service discovery
  skipDirectories: []
  # External overlay network name for all stacks
  network: ""
  # Network driver (default: "overlay")
  networkDriver: "overlay"

# Rendering settings for env var interpolation
render:
  # Output directory for rendered files (default: ".rendered")
  outputDirectory: ".rendered"

# Environment file settings
env:
  # Active .env file name (default: ".env")
  activeName: ".env"
  # Allow plaintext profile env files (default: false)
  allowPlaintextProfiles: false

# (Optional) Secrets management with SOPS/age
# secrets:
#   encryptedFileName: ".env.enc"

# (Optional) Override file configuration
# overrides:
#   autoDiscoverProfiles: true
#   exclude: []

# (Optional) Command-specific defaults
# commands:
#   up:
#     followLogs: true
#   reload:
#     followLogs: false
#     autoGenerate: true
#     forceServiceUpdate: false
`;

const MINIMAL_TEMPLATE = `# stackctl minimal configuration
# Generated by \`stackctl init --preset minimal\`
# See https://github.com/AniTrend/stackctl for documentation

project: ""

stack:
  directory: "stacks"
  names:
    - "app"
  network: ""

render:
  outputDirectory: ".rendered"

env:
  activeName: ".env"
`;

// ---------------------------------------------------------------------------
// Presets
// ---------------------------------------------------------------------------

const PRESETS: Record<string, string> = {
  minimal: MINIMAL_TEMPLATE,
  standard: TEMPLATE,
};

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

/**
 * Generate one or more `.stackctl` configuration files.
 */
export async function initConfig(options: InitOptions): Promise<InitResult> {
  const cwd = options.cwd ?? Deno.cwd();
  const result: InitResult = { written: [], errors: [] };

  // Pick the template
  let template = TEMPLATE;
  if (options.preset && PRESETS[options.preset]) {
    template = PRESETS[options.preset];
  } else if (options.preset) {
    result.errors.push(
      `Unknown preset: "${options.preset}". Available: ${Object.keys(PRESETS).join(", ")}`,
    );
    return result;
  }

  // Auto-detect layout from docker-compose files
  if (options.detect) {
    template = await applyDetection(template, cwd);
  }

  // Write base config (validated before write)
  const basePath = join(cwd, ".stackctl");
  await writeConfigFile(basePath, template, options, result);

  // Write profile config if requested (uses minimal profile template)
  if (options.profile) {
    const profileContent = buildProfileTemplate(options.profile);
    const profilePath = join(cwd, `.stackctl.${options.profile}`);
    await writeConfigFile(profilePath, profileContent, options, result);
  }

  // Handle --write-gitignore
  if (options.writeGitignore) {
    await appendGitignore(cwd, result);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Profile template
// ---------------------------------------------------------------------------

function buildProfileTemplate(profileName: string): string {
  return `# stackctl profile overlay for '${profileName}'
# Generated by \`stackctl init --profile ${profileName}\`

profile: "${profileName}"

# (Optional) Override any base config fields below.
# Only specify the sections you want to override - profile files
# are merged on top of the base .stackctl config.
#
# Example:
#   stack:
#     network: "dev-net"
#   env:
#     activeName: ".env.dev"
`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function writeConfigFile(
  path: string,
  content: string,
  options: InitOptions,
  result: InitResult,
): Promise<void> {
  const alreadyExists = await exists(path);

  if (alreadyExists && !options.force) {
    result.errors.push(
      `File already exists: ${path}. Use --force to overwrite.`,
    );
    return;
  }

  // Validate generated template YAML structure before writing
  try {
    const parsed = parseYaml(content) as Record<string, unknown>;
    if (!parsed || typeof parsed !== "object") {
      result.errors.push(
        `Generated config at ${path} resolves to invalid structure`,
      );
      return;
    }
  } catch (err: unknown) {
    result.errors.push(
      `Failed to parse generated config (${path}): ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
    return;
  }

  if (options.dryRun) {
    result.written.push(path);
    return;
  }

  try {
    await Deno.writeTextFile(path, content);
    result.written.push(path);
  } catch (err: unknown) {
    result.errors.push(
      `Failed to write ${path}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * Append stackctl-specific entries to .gitignore.
 */
export async function appendGitignore(
  cwd: string,
  result?: InitResult,
): Promise<void> {
  const gitignorePath = join(cwd, ".gitignore");
  const entries = [
    "# stackctl generated files",
    ".stackctl.local",
    ".stackctl.local.*",
    ".env",
    ".env.*",
    "!.env.example",
  ];

  let existing = "";
  if (await exists(gitignorePath)) {
    existing = await Deno.readTextFile(gitignorePath);
    if (!existing.endsWith("\n")) existing += "\n";
  }

  const newEntries = entries.filter((e) => !existing.includes(e));
  if (newEntries.length === 0) {
    console.log(".gitignore already up to date");
    return;
  }

  const toAppend = (existing ? "\n" : "") + newEntries.join("\n") + "\n";
  await Deno.writeTextFile(gitignorePath, existing + toAppend);
  console.log(`updated: ${gitignorePath}`);

  if (result) {
    result.written.push(gitignorePath);
  }
}

/**
 * Scan the working directory for docker-compose files, subdirectories,
 * fragments, secret files, and env files to pre-populate config values.
 */
async function applyDetection(template: string, cwd: string): Promise<string> {
  const composeFiles: string[] = [];
  const fragments: string[] = [];
  let hasSops = false;
  let hasAgeKey = false;
  let hasEnvExample = false;
  let hasEnvEnc = false;

  for await (const entry of Deno.readDir(cwd)) {
    const name = entry.name;

    if (entry.isFile) {
      if (
        name === "docker-compose.yml" ||
        name === "docker-compose.yaml" ||
        name === "compose.yml" ||
        name === "compose.yaml" ||
        (name.startsWith("docker-compose.") &&
          (name.endsWith(".yml") || name.endsWith(".yaml")))
      ) {
        composeFiles.push(join(cwd, name));
      }

      if (name.toLowerCase().includes("fragment")) {
        fragments.push(name);
      }

      if (name === ".sops.yaml") hasSops = true;
      if (name === ".age-key") hasAgeKey = true;
      if (name === ".env.example") hasEnvExample = true;
      if (name === ".env.enc") hasEnvEnc = true;
    }

    // Scan one level deep in subdirectories
    if (entry.isDirectory) {
      try {
        const subDir = join(cwd, name);
        for await (const subEntry of Deno.readDir(subDir)) {
          if (subEntry.isFile) {
            const subName = subEntry.name;
            if (
              subName === "docker-compose.yml" ||
              subName === "docker-compose.yaml" ||
              subName === "compose.yml" ||
              subName === "compose.yaml" ||
              (subName.startsWith("docker-compose.") &&
                (subName.endsWith(".yml") || subName.endsWith(".yaml")))
            ) {
              composeFiles.push(join(subDir, subName));
            }
            if (subName.toLowerCase().includes("fragment")) {
              fragments.push(join(name, subName));
            }
          }
        }
      } catch {
        // Skip unreadable subdirectories
      }
    }

    // Scan existing stacks/ directory
    if (entry.isDirectory && name === "stacks") {
      try {
        const stacksDir = join(cwd, name);
        for await (const stackEntry of Deno.readDir(stacksDir)) {
          if (stackEntry.isFile) {
            fragments.push(join("stacks", stackEntry.name));
          }
        }
      } catch {
        // Skip unreadable stacks dir
      }
    }
  }

  // Phase 2: Parse compose files
  const stackNames: string[] = [];
  const xStackGroups = new Map<string, string[]>();
  let composeStackKey = "";
  let network = "";

  for (const file of composeFiles) {
    try {
      const raw = await Deno.readTextFile(file);
      const parsed = parseYaml(raw) as Record<string, unknown>;

      if (parsed?.["x-stack"] && !composeStackKey) {
        composeStackKey = parsed["x-stack"] as string;
      }

      if (parsed?.services && typeof parsed.services === "object") {
        const services = parsed.services as Record<
          string,
          Record<string, unknown>
        >;
        for (const [svcName, svcDef] of Object.entries(services)) {
          if (!stackNames.includes(svcName)) {
            stackNames.push(svcName);
          }

          const xStack = svcDef?.["x-stack"] as string | undefined;
          if (xStack) {
            const existing = xStackGroups.get(xStack) ?? [];
            if (!existing.includes(svcName)) existing.push(svcName);
            xStackGroups.set(xStack, existing);
          }
        }
      }

      if (!network && parsed?.networks && typeof parsed.networks === "object") {
        const nets = parsed.networks as Record<string, unknown>;
        const keys = Object.keys(nets);
        const custom = keys.find(
          (k) => k !== "default" && k !== "bridge" && k !== "host",
        );
        if (custom) network = custom;
        else if (keys.length > 0) {
          const first = keys[0];
          if (first !== "default") network = first;
        }
      }
    } catch {
      // Skip unparseable files
    }
  }

  if (
    composeFiles.length === 0 && fragments.length === 0 && !hasEnvExample &&
    !hasEnvEnc
  ) {
    return template;
  }

  // Phase 3: Inject detected values
  let result = template;

  const finalStackNames = xStackGroups.size > 0 ? Array.from(xStackGroups.keys()) : stackNames;

  if (finalStackNames.length > 0) {
    const namesYaml = finalStackNames.map((n) => `      - "${n}"`).join("\n");
    result = result.replace(
      /(\n)(\s+)names:\n(\s+- "example".*\n)+/,
      `$1$2names:\n${namesYaml}\n`,
    );
  }

  if (network) {
    result = result.replace(
      /(\n)(\s+)network: ""/,
      `$1$2network: "${network}"`,
    );
  }

  if (composeStackKey && composeStackKey !== "x-stack") {
    result = result.replace(
      /composeStackKey: "x-stack"/,
      `composeStackKey: "${composeStackKey}"`,
    );
  }

  const dirName = basename(cwd);
  if (dirName && dirName !== "." && dirName !== "/") {
    result = result.replace(
      /^project: ""$/m,
      `project: "${dirName}"`,
    );
  }

  const discoveries: string[] = [];
  if (fragments.length > 0) {
    discoveries.push(
      `# Detected fragments:\n#   ${fragments.join("\n#   ")}`,
    );
  }
  if (hasSops) discoveries.push("# Detected: .sops.yaml (secrets tooling)");
  if (hasAgeKey) discoveries.push("# Detected: .age-key (age identity)");
  if (hasEnvExample) discoveries.push("# Detected: .env.example");
  if (hasEnvEnc) {
    discoveries.push("# Detected: .env.enc (encrypted env file)");
  }

  if (discoveries.length > 0) {
    result = result.trimEnd() + "\n\n" + discoveries.join("\n") + "\n";
  }

  return result;
}
