import { assertEquals, assertStringIncludes } from "@std/assert";
import { parse as parseYaml } from "@std/yaml";
import { initConfig } from "./init.ts";
import { join } from "@std/path";

Deno.test("initConfig: default template contains expected sections", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    const result = await initConfig({ cwd: tmpDir, dryRun: false });
    assertEquals(result.errors.length, 0);
    assertEquals(result.written.length, 1);
    assertEquals(result.written[0], join(tmpDir, ".stackctl"));

    const content = await Deno.readTextFile(join(tmpDir, ".stackctl"));
    assertStringIncludes(content, "project:");
    assertStringIncludes(content, "stack:");
    assertStringIncludes(content, "directory:");
    assertStringIncludes(content, "names:");
    assertStringIncludes(content, "network:");
    assertStringIncludes(content, "render:");
    assertStringIncludes(content, "outputDirectory:");
    assertStringIncludes(content, "env:");
    assertStringIncludes(content, "activeName:");
    assertStringIncludes(content, "Generated by `stackctl init`");
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});

Deno.test("initConfig: template is valid YAML", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    const result = await initConfig({ cwd: tmpDir, dryRun: false });
    assertEquals(result.errors.length, 0);

    const content = await Deno.readTextFile(join(tmpDir, ".stackctl"));
    // Should parse without throwing
    const parsed = parseYaml(content) as Record<string, unknown>;
    assertEquals(typeof parsed, "object");
    assertEquals(parsed !== null, true);
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});

Deno.test("initConfig: dry-run does not write files", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    const result = await initConfig({ cwd: tmpDir, dryRun: true });
    assertEquals(result.errors.length, 0);
    assertEquals(result.written.length, 1);
    assertEquals(result.written[0], join(tmpDir, ".stackctl"));

    // Verify file was NOT actually written
    try {
      await Deno.stat(join(tmpDir, ".stackctl"));
      // Should not reach here - file should not exist
      assertEquals(true, false, "file should not exist in dry-run mode");
    } catch {
      // Expected: file does not exist
    }
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});

Deno.test("initConfig: force overwrites existing file", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    // First write an existing file
    const existingPath = join(tmpDir, ".stackctl");
    await Deno.writeTextFile(existingPath, "# existing config");

    // Without force, should error
    const resultNoForce = await initConfig({ cwd: tmpDir, force: false, dryRun: false });
    assertEquals(resultNoForce.errors.length, 1);
    assertEquals(resultNoForce.errors[0].includes("already exists"), true);

    // With force, should succeed
    const resultForce = await initConfig({ cwd: tmpDir, force: true, dryRun: false });
    assertEquals(resultForce.errors.length, 0);
    assertEquals(resultForce.written.length, 1);

    // Verify content was overwritten
    const content = await Deno.readTextFile(existingPath);
    assertStringIncludes(content, "Generated by `stackctl init`");
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});

Deno.test("initConfig: detection finds docker-compose files", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    // Create a docker-compose.yml with services and networks
    const composeYml = join(tmpDir, "docker-compose.yml");
    await Deno.writeTextFile(
      composeYml,
      `
services:
  web:
    image: nginx
  api:
    image: my-api
networks:
  frontend:
    driver: overlay
`,
    );

    const result = await initConfig({ cwd: tmpDir, detect: true, dryRun: false });
    assertEquals(result.errors.length, 0);

    const content = await Deno.readTextFile(join(tmpDir, ".stackctl"));
    // Should have detected service names
    assertStringIncludes(content, "web");
    assertStringIncludes(content, "api");
    // Should have detected network
    assertStringIncludes(content, "frontend");
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});

Deno.test("initConfig: preset minimal produces valid template", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    const result = await initConfig({ cwd: tmpDir, preset: "minimal", dryRun: false });
    assertEquals(result.errors.length, 0);
    assertEquals(result.written.length, 1);

    const content = await Deno.readTextFile(join(tmpDir, ".stackctl"));
    // Should be parseable YAML
    const parsed = parseYaml(content) as Record<string, unknown>;
    assertEquals(parsed.project, "");
    assertEquals((parsed.stack as Record<string, unknown>).names, ["app"]);
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});

Deno.test("initConfig: unknown preset returns error", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    const result = await initConfig({ cwd: tmpDir, preset: "nonexistent" });
    assertEquals(result.errors.length, 1);
    assertEquals(result.errors[0].includes("Unknown preset"), true);
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});

Deno.test("initConfig: profile flag writes additional profile file", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    const result = await initConfig({ cwd: tmpDir, profile: "dev", dryRun: false });
    assertEquals(result.errors.length, 0);
    assertEquals(result.written.length, 2);
    assertEquals(result.written[0], join(tmpDir, ".stackctl"));
    assertEquals(result.written[1], join(tmpDir, ".stackctl.dev"));

    // Verify both files exist
    await Deno.stat(join(tmpDir, ".stackctl"));
    await Deno.stat(join(tmpDir, ".stackctl.dev"));
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});

Deno.test("initConfig: round-trip: generated YAML is parseable and valid", async () => {
  const tmpDir = await Deno.makeTempDir({ prefix: "stackctl-init-test-" });
  try {
    // Generate
    const result = await initConfig({ cwd: tmpDir, dryRun: false });
    assertEquals(result.errors.length, 0);

    // Parse
    const content = await Deno.readTextFile(join(tmpDir, ".stackctl"));
    const parsed = parseYaml(content) as Record<string, unknown>;

    // Verify key structure
    assertEquals(typeof parsed.project, "string");
    assertEquals(typeof parsed.stack, "object");
    assertEquals(typeof parsed.render, "object");
    assertEquals(typeof parsed.env, "object");
  } finally {
    await Deno.remove(tmpDir, { recursive: true });
  }
});
